# frontend/Dockerfile
FROM node:18-alpine

WORKDIR /app

# Копирование package.json и package-lock.json
COPY package*.json ./

# Установка зависимостей
RUN npm install -g expo-cli && npm install

# Копирование всего проекта
COPY . .

# Команда запуска
CMD ["npm", "start"]