services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: edik
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fastapi
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U edik -d fastapi"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: .
      dockerfile: ./app/backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql+asyncpg://edik:123456@postgres:5432/fastapi"

  frontend:
    build: 
      context: .
      dockerfile: ./app/Dockerfile  # Укажите путь к Dockerfile фронтенда
    ports:
      - "3000:3000"
    depends_on:
      - backend